### ISSUE TITLE
Authorization failed. The request you have made requires authentication.

### ISSUE THREAD

**Issue by chetom** [vexxhost/keystone-keycloak-backend#4]
Docker was built as instructed:
$ docker compose up -d

Test:

A) 
Login and list user -> Default domain.
testrc: 
export OS_AUTH_URL=http://0.0.0.0:15000/
export OS_PROJECT_DOMAIN_NAME=Default
export OS_PROJECT_NAME=admin
export OS_USER_DOMAIN_NAME=Default
export OS_USERNAME=admin
export OS_PASSWORD=admin

```
$ source hack/testrc
$ openstack user list

openstack user list 
+----------------------------------+-------+
| ID                               | Name  |
+----------------------------------+-------+
| 055f91c3c7ab4bd289ebc1900bf9d1f8 | admin |
+----------------------------------+-------+
```
B)
Login and list user -> keycloak domain:
```
$ openstack role assignment list --name
+-------+----------------+-------+-------------------+----------+--------+-----------+
| Role  | User           | Group | Project           | Domain   | System | Inherited |
+-------+----------------+-------+-------------------+----------+--------+-----------+
| admin | admin@Default  |       | admin@Default     |          |        | False     |
| admin | admin@keycloak |       | keycloak@keycloak |          |        | False     |
| admin | admin@Default  |       |                   | keycloak |        | False     |
| admin | admin@keycloak |       |                   | keycloak |        | False     |
| admin | admin@Default  |       |                   |          | all    | False     |
+-------+----------------+-------+-------------------+----------+--------+-----------+

$ openstack role assignment list 
+----------------------------------+--------------------------------------+-------+----------------------------------+----------------------------------+--------+-----------+
| Role                             | User                                 | Group | Project                          | Domain                           | System | Inherited |
+----------------------------------+--------------------------------------+-------+----------------------------------+----------------------------------+--------+-----------+
| be7c2c8c560848959ced7922ec6aaa2f | 055f91c3c7ab4bd289ebc1900bf9d1f8     |       | b722b7ac6c9546389fb572d2d62d7e55 |                                  |        | False     |
| be7c2c8c560848959ced7922ec6aaa2f | 5a64ab8f-6e21-4311-94e5-363c8e454f70 |       | cdaf5449dd8848e8862a9f0ef71c9850 |                                  |        | False     |
| be7c2c8c560848959ced7922ec6aaa2f | 055f91c3c7ab4bd289ebc1900bf9d1f8     |       |                                  | 682dd71bb256444db7d25c1b5d8168c5 |        | False     |
| be7c2c8c560848959ced7922ec6aaa2f | 5a64ab8f-6e21-4311-94e5-363c8e454f70 |       |                                  | 682dd71bb256444db7d25c1b5d8168c5 |        | False     |
| be7c2c8c560848959ced7922ec6aaa2f | 055f91c3c7ab4bd289ebc1900bf9d1f8     |       |                                  |                                  | all    | False     |
+----------------------------------+--------------------------------------+-------+----------------------------------+----------------------------------+--------+-----------+


Keystone is able to get users from Keycloak.

$ openstack user list --domain keycloak 
+--------------------------------------+-------+
| ID                                   | Name  |
+--------------------------------------+-------+
| 5a64ab8f-6e21-4311-94e5-363c8e454f70 | admin |
| 02a67cf0-4a33-4c95-82d3-fab904bad64a | test  |
+--------------------------------------+-------+



```
adminkeycloakrc: 
export OS_AUTH_URL=http://0.0.0.0:15000/
export OS_PROJECT_DOMAIN_NAME=keycloak
export OS_PROJECT_NAME=keycloak
export OS_USER_DOMAIN_NAME=keycloak
export OS_USERNAME=admin
export OS_PASSWORD=admin

```
$ source adminkeycloakrc
$ openstack user list
The request you have made requires authentication. (HTTP 401) (Request-ID: req-b45536e2-29ba-45f2-8212-430fa65c0724).
```
LOG from Keystone Docker:
[pid: 1|app: 0|req: 11/11] 172.18.0.1 () {28 vars in 398 bytes} [Wed Aug  9 10:26:11 2023] GET / => generated 263 bytes in 3 msecs (HTTP/1.1 300) 5 headers in 208 bytes (1 switches on core 0)
2023-08-09 10:26:11.655 1 WARNING keystone.server.flask.application [None req-5d655b23-d4b7-476a-a1fb-43e52f096fae - - - - - -] Authorization failed. The request you have made requires authentication. from 172.18.0.1: keystone.exception.Unauthorized: The request you have made requires authentication.
[pid: 1|app: 0|req: 12/12] 172.18.0.1 () {32 vars in 480 bytes} [Wed Aug  9 10:26:11 2023] POST /v3/auth/tokens => generated 109 bytes in 70 msecs (HTTP/1.1 401) 5 headers in 226 bytes (1 switches on core 0)

**Comment by mnaser** [comment]
hey @chetom !

i think the issue here is that we disable auth by default, because the idea of this is to make you use some other form of external factor to drive auth via openidc (but the user list is pulled through this).  this way, you can enforce mfa/etc through there.

question: do you have a use case where you actually need to auth using keycloak usernames directly? perhaps we can make this an opt-in thing, but i would feel better suggesting using oidc for auth.

**Comment by chetom** [comment]
Ok, I should have looked at the code.
Regarding the question We have a case where we want to use keykcloak for all our services and many ldaps connected as backend.
We're testing different solutions.
Your software as a keystone authentication driver seems to be perfect.

**Comment by mnaser** [comment]
I can make a change to allow authenticating via Keycloak.. I do wonder if there is a way to check passwords via the API.. do you know @chetom ?

**Comment by chetom** [comment]
I appreciate it very much.
I've done some searching and came across a fairly recent article on the RedHat webpages. 
https://developers.redhat.com/blog/2020/11/24/authentication-and-authorization-using-the-keycloak-rest-api
or
https://stackoverflow.com/questions/71463619/can-i-check-if-the-userid-and-password-are-valid-in-keyclock
That would be ok for me.

**Comment by mnaser** [comment]
@chetom I currently don't have the bandwidth (in the close term) to expand onto this, do you know if you have some spare cycles to put into this?  I can help review code as well.

I think the first option might not work since it is relying on an existing JWT, but the latter could be a good workaround but it would require a client to be created to run those 'validation' tests against.

**Comment by chetom** [comment]
@mnaser Thank you. I appreciate your contribution. Before I start, I need to consider within the organization whether to work on the keystone keycloak driver or modify the keystone ldap driver. The Keycloak driver still seems to be the best solution.
I'll let you know in a few weeks.

**Comment by mnaser** [comment]
@chetom have you had some chance to discuss this internally?  i'd love to see what i can do to get more people to use it. :)

**Comment by chetom** [comment]
I have just wrote an email to you. I don't know if this thread is the right place to discuss it. what do you think? Do you mind if I close this thread.
